name: "PytorchImpute"
optimizer_name: "Adam"
loss_name: "MSELoss"
model_name: "FiveLayerImputation"
lr: .001
weight_decay: 0
device: "cuda"
seed: 42
epochs: 50
batch_size: 256
experiment_name: "Five Layer Imputation"
experiment_description: "Impute with a five layer network"
log_progress: True
train_fraction: .8
save_path: "logs/models"
