name: saged
channels:
  - pytorch
  - nvidia
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1.74
  - curl=7.76.1
  - flake8=3.9.2
  - ipywidgets
  - jupyter=1.0.0
  - jupyterlab_widgets=1.0.0
  - nbconvert=6.0.7
  - neptune-client=0.9.16
  - notebook=6.4.0
  - numpy=1.20.3
  - optuna=2.1.0
  - pandas=1.0.5
  - pip=20.1.1
  - pyflakes=2.3.1
  - pytest=5.4.3
  - pytest-cov=2.10.1
  - python=3.7.10
  - pytorch=1.8.0
  - pyyaml=5.4.1
  - r
  - r-assertthat
  - r-base
  - r-dplyr
  - r-tibble
  - r-rcurl
  - ratelimiter=1.2.0
  - requests=2.24.0
  - rpy2
  - scikit-learn=0.24.2
  - scipy=1.5.3
  - setuptools=49.6.0
  - snakemake=6.0
  - svgutils=0.3.4
  - tqdm=4.60.0
  - umap-learn
  - urllib3=1.25.11
  - yaml=0.2.5
  - pip:
    - configparser==5.0.0
    - h5py==2.10.0
    - keras==2.3.1
    - performer-pytorch==1.0.11
    - ponyo==0.6.1
    - scikit-misc==0.1.4
    - tensorboard==1.15.0
    - tensorflow==1.15.4
    - transformers==3.0.0
