name: saged
channels:
  - r
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconductor-annotate=1.64.0
  - bioconductor-annotationdbi=1.48.0
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-genefilter=1.68.0
  - bioconductor-iranges=2.20.0
  - bioconductor-limma=3.42.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-sva=3.18.0
  - configargparse=1.2.3
  - coverage=5.2.1
  - coveralls=2.1.2
  - cudatoolkit=10.1.243
  - curl=7.68.0
  - ipywidgets=7.5.1
  - jsonref=0.2
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - matplotlib-base=3.3.1
  - mypy=0.782
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - neptune-client=0.4.117
  - networkx=2.4
  - notebook=6.0.3
  - numpy=1.18.5
  - pandas=1.0.5
  - pillow=7.2.0
  - pip=20.1.1
  - plotnine=0.7.0
  - pytest=5.4.3
  - pytest-cov=2.10.1
  - python=3.7
  - pytorch=1.4.0
  - qtpy=1.9.0
  - r=3.6.0
  - r-assertthat=0.2.1
  - r-base=3.6.1
  - r-bit=1.1_14
  - r-bit64=0.9_7.1
  - r-bitops=1.0_6
  - r-blob=1.1.1
  - r-boot=1.3_20
  - r-class=7.3_15
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-dbi=1.0.0
  - r-digest=0.6.18
  - r-foreign=0.8_71
  - r-kernsmooth=2.23_15
  - r-lattice=0.20_38
  - r-magrittr=1.5
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-memoise=1.1.0
  - r-mgcv=1.8_28
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-prettyunits=1.0.2
  - r-rcpp=1.0.1
  - r-rcurl=1.95_4.12
  - r-recommended=3.6.0
  - r-rpart=4.1_15
  - r-rsqlite=2.1.2
  - r-spatial=7.3_11
  - r-survival=2.44_1.1
  - r-xml=3.98_1.19
  - r-xtable=1.8_4
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.2.0
  - rpy2=3.3.2
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - snakemake=5.5.4
  - snakemake-minimal=5.5.4
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tqdm=4.46.1
  - urllib3=1.25.9
  - yaml=0.2.5
  - pip:
    - configparser==5.0.0
    - pyyaml==5.3.1
    - ponyo==0.5
