name: Tybalt
seed: 42
# Hyperparameters used are from https://github.com/greenelab/simulate-expression-compendia/blob/d707321346de48de5e63cf251280bdf9372be59c/configs/config_Pa_sample_combat.tsv
lr: 0.001
batch_size: 100
epochs: 100
kappa: .01
intermediate_dim: 2500
latent_dim: 30
epsilon_std: 1.0
val_frac: .1
