name: "PytorchSupervised"
optimizer_name: "Adam"
loss_name: "CrossEntropyLoss"
model_name: "DeepClassifier"
lr: .00001
l2_penalty: 0
device: "cuda"
seed: 42
epochs: 50
batch_size: 16
experiment_name: "5 Layer classifier"
experiment_description: "Train a supervised pytorch model"
log_progress: True
train_fraction: .8
save_path: "logs/models/deep_net.pt"
clip_grads: True
final_layer_name: "fc5"

# config.input_size and config.output_size should be set dynamically
