name: autopy-lot
on: [pull-request]

jobs:
  build:
    name: autopy-lot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: autopy-lot 
        uses: deep5050/autopy-lot@1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check: 'latest'
          input_type: 'ipynb'
          output_type: 'py'
          output_dir: './notebook/converted'
